name: Docker Build & Publish
description: Builds Docker Image and Pushes it to a Registry

inputs:
  IMAGE_NAME:
    required: false
    default: "latest"
  IMAGE_TAG:
    required: false
    default: "ghcr.io/${{ github.repository }}"
  IMAGE_REGISTRY:
    required: false
    default: ghcr.io
  DOCKER_USERNAME:
    required: false
    default: ${{ github.repository_owner }}
  DOCKER_PASSWORD:
    required: true
  DOCKERFILE_PATH:
    required: false
    default: Dockerfile

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build Docker Image
      shell: bash
      run: docker build -f ${{ inputs.DOCKERFILE_PATH }} -t docker_image .

    - name: Login to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.IMAGE_REGISTRY }}
        username: ${{ inputs.DOCKER_USERNAME }}
        password: ${{ inputs.DOCKER_PASSWORD }}

    - name: Push Image to Registry
      shell: bash
      run: |
        IMAGE_PATH="${{ inputs.IMAGE_REGISTRY }}/${{ inputs.IMAGE_NAME }}"

        docker tag docker_image:latest ${IMAGE_PATH}:latest
        docker tag docker_image:latest ${IMAGE_PATH}:${{ inputs.IMAGE_TAG }}

        docker push ${IMAGE_PATH}:latest
        docker push ${IMAGE_PATH}:${{ inputs.IMAGE_TAG }}
