name: Docker Build & Publish
description: Builds Docker Image and Pushes it to a Registry

inputs:
  PUBLISH:
    required: false
    default: false
  IMAGE_NAME:
    required: true
  DOCKER_USERNAME:
    required: false
  DOCKER_PASSWORD:
    required: false

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build Docker Image
      shell: bash
      run: docker build -t docker_image .

    - name: Login to GitHub Container Registry
      if: ${{ inputs.PUBLISH == true }}
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ inputs.DOCKER_USERNAME }}
        password: ${{ inputs.DOCKER_PASSWORD }}

    - name: Create Deploy Tag
      if: ${{ inputs.PUBLISH == true }}
      shell: bash
      run: |
        DEPLOY_TAG=v$(date +%Y.%m.%d-%H.%M.%S)

        git tag ${DEPLOY_TAG}
        git push --tags

    - name: Build & Push Docker image
      if: ${{ inputs.PUBLISH == true }}
      shell: bash
      run: |
        DEPLOY_TAG=$(git tag -l --sort -v:refname | head -n1)

        docker tag docker_image:latest ${{ inputs.IMAGE_NAME }}:latest
        docker tag docker_image:latest ${{ inputs.IMAGE_NAME }}:${DEPLOY_TAG}

        docker push ${{ inputs.IMAGE_NAME }}:latest
        docker push ${{ inputs.IMAGE_NAME }}:${DEPLOY_TAG}
