name: Docker Build & Publish
description: Builds Docker Image and Pushes it to a Registry

inputs:
  PUBLISH:
    required: false
    default: false
  IMAGE_NAME:
    required: true

runs:
  using: composite
  steps:
  - name: Checkout repository
    uses: actions/checkout@v4

  - name: Build Docker Image
    run: docker build -t docker_image .

  - name: Login to GitHub Container Registry
    if: ${{ inputs.PUBLISH }}
    uses: docker/login-action@v3
    with:
      registry: ghcr.io
      username: ${{ github.repository_owner }}
      password: ${{ secrets.GITHUB_TOKEN }}

  - name: Create Deploy Tag
    if: ${{ inputs.PUBLISH }}
    shell: bash
    run: |
      DEPLOY_TAG=v$(git log -1 --format="%at" | xargs -I{} date -d @{} +%Y.%m.%d-%H.%M.%S)

      git tag ${DEPLOY_TAG}
      git push --tags

  - name: Build & Push Docker image
    if: ${{ inputs.PUBLISH }}
    shell: bash
    run: |
      DEPLOY_TAG=$(git describe --tags --abbrev=0)

      docker tag docker_image:latest ${{ inputs.IMAGE_NAME }}:latest
      docker tag docker_image:latest ${{ inputs.IMAGE_NAME }}:${DEPLOY_TAG}

      docker push ${{ inputs.IMAGE_NAME }}:latest
      docker push ${{ inputs.IMAGE_NAME }}:${DEPLOY_TAG}
