name: Deploy
description: Deploy to environment

inputs:
  IMAGE_NAME:
    description: Image name to be deployed
    required: false
    default: "ghcr.io/${{ github.repository }}"
  IMAGE_TAG:
    description: Image tag to be deployed
    required: false
    default: "latest"
  REPO_NAME:
    description: Name of the repo with the manifests
    required: true
  MANIFEST_PATH:
    description: Path to the YAML manifest to update the image
    required: true
  TOKEN:
    description: PAT token with access to the manifest repo
    required: false
  EVENT_TYPE:
    description: Name of the event sent to the remote workflow
    required: true

runs:
  using: composite
  steps:
  - name: Checkout repository
    uses: actions/checkout@v4

  - name: Get Latest Release
    shell: bash
    run: |
      RELEASE_LINK=$(curl https://api.github.com/repos/rhrlima/axum-api/releases/latest | jq -r '.html_url')
      echo "RELEASE_LINK=$(echo $RELEASE_LINK)" >> $GITHUB_ENV 

  - name: Summary
    shell: bash
    run: |
      echo "EVENT TYPE: ${{ inputs.EVENT_TYPE }}"
      echo "IMAGE: ${{ inputs.IMAGE_NAME }}:${{ inputs.IMAGE_TAG }}"
      echo "REPOSITORY: ${{ inputs.REPO_NAME }}"
      echo "MANIFEST PATH: ${{ inputs.MANIFEST_PATH }}"
      echo "LATEST RELEASE: ${{ env.RELEASE_LINK }}"

  - name: Repository Dispatch
    uses: peter-evans/repository-dispatch@v3
    with:
      token: ${{ inputs.TOKEN }}
      repository: ${{ inputs.REPO_NAME }}
      event-type: ${{ inputs.EVENT_TYPE }}
      client-payload: |
        {
          "event_type": "${{ inputs.EVENT_TYPE }}",
          "image_tag": "${{ inputs.IMAGE_TAG }}",
          "image_name": "${{ inputs.IMAGE_NAME }}",
          "manifest_path": "${{ inputs.MANIFEST_PATH }}",
          "latest_release": "${{ env.RELEASE_LINK }}"
        }
