name: Build & Publish

on: [workflow_dispatch]

env:
  DEPLOY_REPO_NAME: "rhrlima/app-manifests"
  DEPLOY_MANIFEST_PATH: "axum-api/deployment.yaml"

jobs:
  build_and_test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Lint
        run: echo "Linting code"

      - name: Setup Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: "1.70.0"

      - name: Build Rust application
        run: cargo build --release

      - name: Light Tests
        run: cargo test --release

  heavy_tests:
    name: Heavy Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: "1.70.0"

      - name: Heavy Tests
        run: cargo test --release

  docker_build_and_publish:
    name: Docker Build & Publish
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - uses: rhrlima/axum-api/.github/actions/docker@develop
        with:
          IMAGE_NAME: "${{ vars.REGISTRY_DOMAIN }}/${{ vars.REGISTRY_NAME }}"
          DOCKER_USERNAME: ${{ github.repository_owner }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

  deploy_dev:
    name: Deploy Dev
    # needs: docker_build_and_publish
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Repository Dispatch
        uses: rhrlima/axum-api/.github/actions/deploy@develop
        with:
          # test only with required parameters
          REPO_NAME: ${{ env.DEPLOY_REPO_NAME }}
          MANIFEST_PATH: "dev/${{ env.DEPLOY_MANIFEST_PATH }}"
          EVENT_TYPE: "[DEV] Deploy Axum API"
          TOKEN: ${{ secrets.ACTIONS_KEY }}

  # deploy_stage:
  #   name: Deploy Stage
  #   needs: deploy_dev
  #   runs-on: ubuntu-latest
  #   environment: staging

  #   # MAIN or DEVELOP
  #   if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'

  #   steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v4

  #   - name: Get Image Tag
  #     shell: bash
  #     run: |
  #       git fetch --tags --depth=10
  #       echo "IMAGE_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_ENV

  #   - name: Repository Dispatch
  #     uses: ./.github/jobs/deploy
  #     with:
  #       # test providing optional parameters
  #       REPO_NAME: ${{ env.DEPLOY_REPO_NAME }}
  #       MANIFEST_PATH: "stage/${{ env.DEPLOY_MANIFEST_PATH }}"
  #       IMAGE_NAME: "${{ vars.REGISTRY_DOMAIN }}/${{ vars.REGISTRY_NAME }}"
  #       IMAGE_TAG: ${{ env.IMAGE_TAG }}
  #       EVENT_TYPE: "[STAGE] Deploy Axum API"
  #       TOKEN: ${{ secrets.ACTIONS_KEY }}
