name: Build & Test

# limit this action to modifications to rust related files
on:
  push:
    paths:
      - 'src/**'
      - 'Cargo.toml'
      - 'Cargo.lock'

jobs:
  build_and_test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Lint
        run: echo "Linting code"

      - name: Build Rust application
        run: cargo build --release

      - name: Light Tests
        run: cargo test --release

      - name: Heavy Tests
        # only MAIN branch
        if: github.ref == 'refs/heads/main'
        run: cargo test --release
