name: Rust Build and Docker Publish

on:
  push:
    branches:
      - main

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Rust
      uses: actions/setup-rust@v1

    - name: Build Rust application
      run: cargo build --release

    - name: Create Deploy Tag
      run: |
        LAST_COMMIT_DT=$(git log -1 --format="%at" | xargs -I{} date -d @{} +%Y.%m.%d-%H.%M.%S)
        echo $LAST_COMMIT_DT > deploys/${{ github.run_id }}/deploy_tag

    - name: Upload Deploy Tag
      uses: actions/upload-artifact@v2
      with:
        name: deploy_tag
        path: deploys/${{ github.run_id }}/deploy_tag
        retention-days: 7

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        push: true
        registry: ghcr.io
        repository: rhrlima/axum-api
        tag_with_ref: $(cat deploys/${{ github.run_id }}/deploy_tag)

  update_argocd_manifest:
    needs: build_and_publish
    runs-on: ubuntu-latest

    steps:
    - name: Checkout app-manifests repository
      uses: actions/checkout@v2
      with:
        repository: rhrlima/app-manifests
        ref: main

    - name: Get Deploy Tag
      uses: actions/download-artifact@v2
      with:
        name: deploy_tag
        path: deploys/${{ github.run_id }}

    - name: Update image tag in app-manifests
      run: |
        sed -i "" "s|newTag:.*|newTag: ghcr.io/rhrlima/axum-api:$(cat deploys/${{ github.run_id }}/deploy_tag)|" dev/axum-api/kustomization.yaml

    - name: Commit and push changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Update image tag to $(cat deploys/${{ github.run_id }}/deploy_tag)"
        git push
