name: Create Tag

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Generate Semantic Version
        id: semver
        uses: rapidstack/PR-Label-Semver-Action@v1.3.6

      - name: Generate new Tag
        run: |
          git tag v${{ steps.semver.outputs.string }}
          git push --tags
