name: Update Version

on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Generate Semantic Version
        id: semver
        uses: rapidstack/PR-Label-Semver-Action@v1.3.6

      - name: Set Version
        run: echo "APP_VERSION=v${{ steps.semver.outputs.string }}" >> $GITHUB_ENV

      - name: Set SemVer in Github Environment
        run: gh variable set APP_VERSION --body $APP_VERSION
        env:
          APP_VERSION: ${{ env.APP_VERSION }}
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
