name: Update Version

on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Generate Semantic Version
        id: semver
        uses: rapidstack/PR-Label-Semver-Action@v1.3.6

      - name: Set Version
        run: |
          echo "v${{ steps.semver.outputs.string }}" > tmp/version
          cat tmp/version

      - name: Upload new Version
        uses: actions/upload-artifact@v4
        with:
          name: version
          path: tmp/version
