name: Create Tag

on:
  pull_request:
    types:
      - created
      - labeled
      - unlabeled
      - merged

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Generate Semantic Version
        id: semver
        uses: rapidstack/PR-Label-Semver-Action@v1.3.6

      - name: Generate new Tag
        if: github.event.pull_request.merged
        run: |
          git tag v${{ steps.semver.outputs.string }}
          git push --tags
