name: Deploy

on: [workflow_dispatch]

env:
  DEPLOY_REPO_NAME: "rhrlima/app-manifests"
  DEPLOY_MANIFEST_PATH: "axum-api/deployment.yaml"

jobs:
  docker_build_and_publish:
    name: Docker Build & Publish
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - uses: rhrlima/axum-api/.github/actions/docker@main
        with:
          IMAGE_NAME: "${{ vars.REGISTRY_DOMAIN }}/${{ vars.REGISTRY_NAME }}"
          DOCKER_USERNAME: ${{ github.repository_owner }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

  deploy_dev:
    name: Deploy Dev
    needs: docker_build_and_publish
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Repository Dispatch
        uses: rhrlima/axum-api/.github/actions/deploy@main
        with:
          REPO_NAME: ${{ env.DEPLOY_REPO_NAME }}
          MANIFEST_PATH: "dev/${{ env.DEPLOY_MANIFEST_PATH }}"
          EVENT_TYPE: "[DEV] Deploy Axum API"
          TOKEN: ${{ secrets.ACTIONS_KEY }}

  publish_release_draft:
    name: Publish Release Draft
    needs: docker_build_and_publish
    runs-on: ubuntu-latest
    permissions:
      # write permission is required to create a github release
      contents: write
      # write permission is required for autolabeler
      # otherwise, read permission is required at least
      pull-requests: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Deploy Tag
        run: |
          git fetch --tags --depth=10
          echo "DEPLOY_TAG=$(git tag -l --sort -v:refname | head -n1)" >> $GITHUB_ENV

      - uses: release-drafter/release-drafter@v6
        with:
          name: Release ${{ env.DEPLOY_TAG }}
          tag: ${{ env.DEPLOY_TAG }}
          publish: true
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
