name: Deploy

on: [workflow_dispatch]

env:
  DEPLOY_REPO_NAME: "rhrlima/app-manifests"
  DEPLOY_MANIFEST_PATH: "axum-api/deployment.yaml"

jobs:
  docker_build_and_publish:
    name: Docker Build & Publish
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - uses: rhrlima/axum-api/.github/actions/docker@develop
        with:
          IMAGE_NAME: "${{ vars.REGISTRY_DOMAIN }}/${{ vars.REGISTRY_NAME }}"
          DOCKER_USERNAME: ${{ github.repository_owner }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

  deploy_dev:
    name: Deploy Dev
    # needs: docker_build_and_publish
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Repository Dispatch
        uses: rhrlima/axum-api/.github/actions/deploy@develop
        with:
          # test only with required parameters
          REPO_NAME: ${{ env.DEPLOY_REPO_NAME }}
          MANIFEST_PATH: "dev/${{ env.DEPLOY_MANIFEST_PATH }}"
          EVENT_TYPE: "[DEV] Deploy Axum API"
          TOKEN: ${{ secrets.ACTIONS_KEY }}
