name: Release Drafter

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: true
      publish:
        type: boolean
        default: false

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      # write permission is required to create a github release
      contents: write
      # write permission is required for autolabeler
      # otherwise, read permission is required at least
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "main"
      - uses: release-drafter/release-drafter@v6
        # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
        with:
          name: Release ${{ github.event.inputs.tag || 'DRAFT' }}
          tag: ${{ github.event.inputs.tag || 'DRAFT' }}
          publish: ${{ github.event.inputs.publish || 'false' }}
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_KEY }}
