name: Deploy Stage

on:
  workflow_dispatch: # manual trigger

jobs:
  stage_deploy:
    name: Stage Deploy
    runs-on: ubuntu-latest

    env:
      DEPLOY_REPO_NAME: rhrlima/app-manifests
      MANIFEST_PATH: stage/axum-api/deployment.yaml

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Fetch Tags
      run: git fetch --tags

    - name: Trigger Deploy
      run: |
        IMAGE_NAME="${{ vars.REGISTRY_DOMAIN }}/${{ vars.REGISTRY_NAME }}"
        IMAGE_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)

        curl -X POST https://api.github.com/repos/${DEPLOY_REPO_NAME}/dispatches \
        -H 'Accept: application/vnd.github.everest-preview+json' \
        -u ${{ secrets.ACTIONS_KEY }} \
        --data '{
          "event_type": "Automated Deploy",
          "client_payload": {
            "image_tag": "'"$IMAGE_TAG"'",
            "image_name": "'"$IMAGE_NAME"'",
            "manifest_path": "'"$MANIFEST_PATH"'"
          }}'
