name: Test

on: [push]

jobs:
  deploy_dev:
    name: Deploy Dev
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Repository Dispatch
        uses: rhrlima/axum-api/.github/actions/deploy@main
        with:
          IMAGE_TAG: ${{ vars.APP_VERSION }}
          REPO_NAME: ${{ vars.DEPLOY_REPO }}
          MANIFEST_PATH: "dev/${{ vars.DEPLOY_MANIFEST }}"
          EVENT_TYPE: "[DEV] Deploy Axum API"
          TOKEN: ${{ secrets.PAT_TOKEN }}
